# Generated by Django 3.0.2 on 2022-07-14 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_otp_code', models.CharField(max_length=6)),
                ('email_otp_code', models.CharField(max_length=6)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('i_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_token',
            },
        ),
    ]
