# Generated by Django 3.0.2 on 2022-07-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('host', models.CharField(max_length=128)),
                ('port', models.CharField(choices=[('587', '587'), ('465', '465'), ('25', '25')], default='465', max_length=8, verbose_name='Port *')),
                ('port_type', models.CharField(choices=[('SSL', 'TLS/SSL'), ('StartTLS', 'STARTTLS'), ('None', 'None')], default='TLS/SSL', max_length=8, verbose_name='Port Type *')),
            ],
            options={
                'db_table': 'email_configuration',
            },
        ),
    ]
