# Generated by Django 3.0.2 on 2022-07-15 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_in_latitude', models.IntegerField()),
                ('punch_in_longitude', models.IntegerField()),
                ('punch_out_latitude', models.IntegerField()),
                ('punch_out_longitude', models.IntegerField()),
                ('punch_in_time', models.DateTimeField()),
                ('punch_out_time', models.DateTimeField()),
                ('i_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
