# Generated by Django 3.0.2 on 2022-07-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0003_auto_20220715_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
