# Generated by Django 3.0.2 on 2022-07-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0004_auto_20220715_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='punch_in_note',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_out_note',
            field=models.CharField(default='', max_length=200),
        ),
    ]
