# Generated by Django 3.0.2 on 2022-07-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0005_auto_20220718_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_in_note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_out_note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
