# Generated by Django 3.0.2 on 2022-07-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0006_auto_20220720_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_in_latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_in_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_out_latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_out_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
