# Generated by Django 3.0.2 on 2022-07-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0007_auto_20220720_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='punch_in_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_out_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
