# Generated by Django 3.0.2 on 2022-07-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0008_auto_20220721_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='punch_in_image',
            new_name='punch_in_image_path',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='punch_out_image',
            new_name='punch_out_image_path',
        ),
    ]
