# Generated by Django 3.0.2 on 2022-08-01 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0011_company_radius'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='company',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='i_company',
            new_name='i_client',
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
    ]
