# Generated by Django 3.1 on 2022-09-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0012_auto_20220801_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='user_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
