# Generated by Django 3.1 on 2022-09-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0013_attendance_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='user_status',
            new_name='user_punch_in_status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='user_punch_out_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
